### ISSUE TITLE
In ZILN loss network, the three activation function are sigmoid, identity and softplus. 

### ISSUE THREAD

**Issue by twostarxx** [google/lifetime_value#1]
In `lifetime_value/notebooks/kaggle_acquire_valued_shoppers_challenge/regression.ipynb` , the output units=3 and activation=relu in the last layer. While in the paper, section 3 mentioned that "three activation functions are sigmoid, identity, and softplus".

**Comment by LichaoLiu666** [comment]
@twostarxx I have the same question. Do you happen to know the answer?
